2025-04-06 01:21:43,766 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FACF37A950>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 01:25:16,584 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FB7EAAA950>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
