ERROR:root:Data integration failed: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001B9C0879510>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
ERROR:root:Data integration failed: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000020669509510>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
ERROR:root:Data integration failed: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000160F5F89510>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 01:21:26,263 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001FFFCD9D590>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 01:25:24,187 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E8672ABF50>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 01:34:40,703 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000291C5F63F50>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 12:51:46,818 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016E676296D0>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 12:56:47,355 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016E6762B710>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 13:01:47,395 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016E67635650>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 13:06:47,440 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016E67637450>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 13:11:47,484 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016E6764D290>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 13:30:12,050 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016E676362D0>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 13:35:12,076 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000016E67635210>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 13:36:39,455 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000203F40D96D0>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 13:41:39,534 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000203F40DB710>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 13:46:39,593 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000203F40E5650>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 13:51:39,648 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000203F40E7450>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 13:56:39,693 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000203F40FD290>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 14:01:39,777 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000203F40E62D0>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 14:06:39,805 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000203F40E5210>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 14:11:39,827 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000203F40DA9D0>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 14:16:39,832 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000203F40FD5D0>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 14:21:39,841 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000203F40FF150>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 14:38:30,948 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000203F4100F90>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 14:42:07,755 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024D120C9810>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 14:47:07,828 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024D120CB850>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 14:52:07,964 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024D120D5790>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 14:57:08,005 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024D120D7590>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 15:02:08,025 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024D120ED390>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 15:07:08,083 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024D120D6550>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 15:12:08,190 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024D120D5350>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 15:17:08,287 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024D120CB650>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 15:22:08,390 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024D120ED790>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 15:28:46,949 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024D120EF290>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 15:33:46,959 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024D120F10D0>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 15:38:47,073 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000024D120EEA50>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 17:35:09,922 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA22FB5290>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 17:40:10,012 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA22FDE290>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 17:45:10,029 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA22FE41D0>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 17:50:10,045 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA22FE5F50>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 17:54:26,637 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CD82145290>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 17:55:10,069 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA22FE7D50>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 17:59:26,723 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CD8216E290>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:00:10,079 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA22FDFE90>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:04:26,757 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CD821741D0>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:05:10,147 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA22FDE110>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:09:26,822 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CD82175F50>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:10:10,176 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA22FE6B50>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:14:26,889 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CD82177D50>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:15:10,192 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA22FE4150>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:19:26,953 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CD8216FE90>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:20:11,505 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA22FEDC90>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:24:26,966 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CD8216E110>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:25:11,530 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA22FEFA90>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:29:27,003 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CD82176B50>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:30:11,560 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA22FE5050>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:34:27,060 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CD82174150>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:35:11,589 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA22FCB2D0>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:39:27,101 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002CD8217DC90>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
2025-04-06 18:40:11,622 - ERROR - Error: HTTPSConnectionPool(host='api.publicapis.org', port=443): Max retries exceeded with url: /entries (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001AA22FDE4D0>: Failed to resolve 'api.publicapis.org' ([Errno 11001] getaddrinfo failed)"))
